version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: bash -c "
      cd src/
      && alembic upgrade head
      && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
    env_file:
      - compose/local/.env
    secrets:
      - api_jwt_private_key
      - api_jwt_public_key
    ports:
      - 8000:8000
    depends_on:
      - pg
    
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass pass
    ports:
      - 6379:6380

  pg:
    image: postgres:14-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database
    expose:
      - 5432
    ports:
      - 5433:5432

secrets:
  api_jwt_private_key:
    file: ./jwtRSA256-private.pem
  api_jwt_public_key:
    file: ./jwtRSA256-public.pem

volumes:
  pg_data: