version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./compose/stage/Dockerfile
    command: bash -c "
      cd src
      && alembic upgrade head
      && python main.py"
    env_file:
      - compose/stage/.env
    secrets:
      - api_jwt_private_key
      - api_jwt_public_key
    ports:
      - 8000:8000
    depends_on:
      - pg

  pg:
    image: postgres:14-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database
    expose:
      - 5432
    ports:
      - 5433:5432

secrets:
  api_jwt_private_key:
    file: ./jwtRSA256-private.pem
  api_jwt_public_key:
    file: ./jwtRSA256-public.pem

volumes:
  pg_data: