version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: bash -c "
      cd src/
      && pipenv run alembic upgrade head
      && pipenv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
    env_file:
      - compose/local/.env
    ports:
      - 8000:8000
    depends_on:
      - pg

  pg:
    image: postgres:14-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database
    expose:
      - 5432
    ports:
      - 5433:5432

volumes:
  pg_data: