version: "3.8"

services:
  pg:
    image: postgres:14-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database
    ports:
      - 5433:5432

volumes:
  pg_data: