apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: localhost:5000/proper-fastapi-startup_api:latest
          command: ["/bin/sh"]
          args: ["-c", "cd src/
            && alembic upgrade head
            && uvicorn main:app --host 0.0.0.0 --port 8000"]
          resources:
            limits:
              memory: "1000M"
              cpu: "100m"
          ports:
            - containerPort: 8000
          env:
            - name: API_PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: pg_host
            - name: API_PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: pg_port
            - name: API_PG_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: pg_sslmode
            - name: API_PG_USER
              valueFrom:
                secretKeyRef:
                  name: api
                  key: pg_user
            - name: API_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api
                  key: pg_password
            - name: API_PG_DB
              valueFrom:
                secretKeyRef:
                  name: api
                  key: pg_database
---
apiVersion: v1
kind: Service
metadata:
  name: pg
  labels:
    app: pg
spec:
  selector:
    app: pg
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: postgres:14-alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api
                  key: pg_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api
                  key: pg_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api
                  key: pg_database
          ports:
            - containerPort: 5432
