"""empty message

Revision ID: 6e5a9efaf1f5
Revises: fad208b62b9d
Create Date: 2022-05-11 17:12:45.142808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5a9efaf1f5'
down_revision = 'fad208b62b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_name')
    )
    op.create_index('sso_authorizations_provider_name_provider_id_user_id_idx', 'sso_authorizations', ['provider_name', 'provider_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sso_authorizations_provider_name_provider_id_user_id_idx', table_name='sso_authorizations')
    op.drop_table('sso_authorizations')
    # ### end Alembic commands ###
